# GET Product
GET http://localhost:4000/checkout/bceb6c31-26b5-45b4-97de-e26196e9633f

###

# POST order with product 1
POST http://localhost:4000/checkout
Content-Type: application/json

{
  "clientId": "87fb6c84-ff9e-4287-bfff-dd166eaf5526",
  "items": [
    {
      "productId": "9eea967e-4ffa-47ac-961c-ef836fb0a181",
      "quantity": 2
    },
    {
      "productId": "5a308c21-2bd0-4dd7-87f7-154af5838377",
      "quantity": 1
    }
  ]
}